FROM rocm/dev-ubuntu-22.04:6.2.4-complete AS base

ENV PATH=/opt/rocm/llvm/bin:$PATH
ENV ROCM_PATH=/opt/rocm
ENV LD_LIBRARY_PATH /opt/rocm/lib:/usr/local/lib:
ENV PYTORCH_ROCM_ARCH=gfx942

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update && apt-get install -y git python3.10-venv
RUN pip install packaging cmake ninja wheel pybind11

FROM base AS build_hipblaslt
RUN git clone https://github.com/ROCm/hipBLASLt
RUN cd hipBLASLt \
    && ./install.sh -d --architecture gfx942 --legacy_hipblas_direct \
    && cd build/release \
    && make package
RUN mkdir -p /app/install && cp /app/hipBLAS-common/build/*.deb /app/install \
    && cp /app/hipBLASLt/build/release/*.deb /app/install

FROM base AS build_rccl
RUN git clone https://github.com/ROCm/rccl
RUN cd rccl \
    && git checkout develop \
    && ./install.sh -p --amdgpu_targets gfx942
RUN mkdir -p /app/install && cp /app/rccl/build/release/*.deb /app/install

FROM base AS build_triton
ARG TRITON_BRANCH="e192dba"
ARG TRITON_REPO="https://github.com/triton-lang/triton.git"
RUN git clone ${TRITON_REPO}
RUN cd triton \
    && git checkout ${TRITON_BRANCH} \
    && cd python \
    && python3 setup.py bdist_wheel --dist-dir=dist
RUN mkdir -p /app/install && cp /app/triton/python/dist/*.whl /app/install

FROM base AS build_amdsmi
RUN cd /opt/rocm/share/amd_smi \
    && pip wheel . --wheel-dir=dist
RUN mkdir -p /app/install && cp /opt/rocm/share/amd_smi/dist/*.whl /app/install

FROM base as build_pytorch
ARG PYTORCH_BRANCH="cedc116"
ARG PYTORCH_VISION_BRANCH="v0.19.1"
ARG PYTORCH_REPO="https://github.com/ROCm/pytorch.git"
ARG PYTORCH_VISION_REPO="https://github.com/pytorch/vision.git"
ARG FA_BRANCH="3cea2fb"
ARG FA_REPO="https://github.com/ROCm/flash-attention.git"
RUN git clone ${PYTORCH_REPO} pytorch
RUN cd pytorch && git checkout ${PYTORCH_BRANCH} && \
    pip install -r requirements.txt && git submodule update --init --recursive \
    && python3 tools/amd_build/build_amd.py \
    && CMAKE_PREFIX_PATH=$(python3 -c 'import sys; print(sys.prefix)') python3 setup.py bdist_wheel --dist-dir=dist \
    && pip install dist/*.whl
RUN git clone ${PYTORCH_VISION_REPO} vision
RUN cd vision && git checkout ${PYTORCH_VISION_BRANCH} \
    && python3 setup.py bdist_wheel --dist-dir=dist \
    && pip install dist/*.whl
RUN git clone ${FA_REPO}
RUN cd flash-attention \
    && git checkout ${FA_BRANCH} \
    && git submodule update --init \
    && MAX_JOBS=64 GPU_ARCHS=${PYTORCH_ROCM_ARCH} python3 setup.py bdist_wheel --dist-dir=dist
RUN mkdir -p /app/install && cp /app/pytorch/dist/*.whl /app/install \
    && cp /app/vision/dist/*.whl /app/install \
    && cp /app/flash-attention/dist/*.whl /app/install

FROM base AS final
RUN --mount=type=bind,from=build_hipblaslt,src=/app/install/,target=/install \
    cd /install && dpkg -i ./*deb
RUN --mount=type=bind,from=build_rccl,src=/app/install/,target=/install \
    cd /install && dpkg -i ./*deb
RUN --mount=type=bind,from=build_triton,src=/app/install/,target=/install \
    cd /install && pip install ./*.whl
RUN --mount=type=bind,from=build_amdsmi,src=/app/install/,target=/install \
    cd /install && pip install ./*.whl
RUN --mount=type=bind,from=build_pytorch,src=/app/install/,target=/install \
    cd /install && pip install ./*.whl